### ISSUE TITLE
Not in bash, in C++ (even if it runs in a terminal)

### ISSUE THREAD

**Issue by Naereen** [Juice805/Minesweeper#1]
Hi,
Could you update the description of your project?
It's misleading to say it's in bash, as it's written in C++!
Even if it is designed to run in a console/terminal, it's **not in Bash**!
Thanks in advance.

**Comment by Naereen** [comment]
Hi,
The README still says "a bash version of Minesweeper".

**Comment by Juice805** [comment]
Thanks! Fixed the Readme
